name: Sync Teams Calendar to Google

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'  # Rodar todo dia útil às 7h da manhã
    - cron: '0 12 * * 1-5' # Rodar todo dia útil ao meio-dia

env:
  TEAMS_ICS_URL: ${{ secrets.TEAMS_ICS_URL }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        run: python calendar_sync.py
